name: ci

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build polygon token oracle backend binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Checkout polygon token oracle backend code
        uses: actions/checkout@v2
        with:
          path: polygon-token-oracle-backend
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get latest version and release
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1 | tr -d v)
          RELEASE=$(git describe --long | cut -f2 -d-)
          echo "build_version=$VERSION" >> $GITHUB_ENV
          echo "build_release=$RELEASE" >> $GITHUB_ENV
        working-directory: polygon-token-oracle-backend

      - name: Build polygon token oracle backend binary for Linux
        run: |
          cd polygon-token-oracle-backend
          go build -ldflags "-s -w" -o backend
        working-directory: polygon-token-oracle-backend

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: polygon-token-oracle-backend/backend
          retention-days: 1